CREATE TABLE IF NOT EXISTS Restaurants (
  RESTAURANT_ID UUID PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL,
  PHOTO VARCHAR(255) NOT NULL,
  CONSTRAINT FK_RESTAURANT_ADDRESS_ID FOREIGN KEY (RESTAURANT_ADDRESS_ID) REFERENCES Restaurants(RESTAURANT_ID)
) 